# Auth Controller Requests

### Sign Up Customer
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "customer@example.com",
  "password": "admin123",
  "username": "customerUser"
}

### Sign Up Admin
# Only for Admin, Require [ADMIN_TOKEN]
POST http://localhost:3000/auth/signup/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczNDM5NTU5NywiZXhwIjoxNzM0Mzk5MTk3fQ.fITpE6hLN9EjtdOlM0hw04fmZ2sZ1FJ7zEDvsZrTy9Y

{
  "email": "admin2@example.com",
  "password": "admin123",
  "username": "adminUser"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin2@example.com",
  "password": "admin123"
}

### Get User Profile (Re    quires JWT Token in Cookie)
GET http://localhost:3000/auth/profile
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJpYXQiOjE3MzQzOTY3OTgsImV4cCI6MTczNDQwMDM5OH0.GuWAV5R4Go2gWdIBJbf0YP-ihDI1qASejo0AXItSgag

### Logout
POST http://localhost:3000/auth/logout
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJpYXQiOjE3MzQzOTY3OTgsImV4cCI6MTczNDQwMDM5OH0.GuWAV5R4Go2gWdIBJbf0YP-ihDI1qASejo0AXItSgag


# User Controller Requests

### Get All Users
# Only for Admin, Require [ADMIN_TOKEN]
GET http://localhost:3000/user/all
Authorization: Bearer <PASTE_YOUR_ACCESS_TOKEN_HERE>

### Get User by ID
GET http://localhost:3000/user/8
Authorization: Bearer <PASTE_YOUR_ACCESS_TOKEN_HERE>

### Update User
PATCH http://localhost:3000/user/8
Content-Type: application/json
Authorization: Bearer <PASTE_YOUR_ACCESS_TOKEN_HERE>

{
  "username": "UpdatedCustomerName"
}

### Delete User
# Only for Admin, Require [ADMIN_TOKEN]
DELETE http://localhost:3000/user/7
Authorization: Bearer <PASTE_YOUR_ACCESS_TOKEN_HERE>

# Google Controller Requests

### Google Login
GET http://localhost:3000/auth/google

### Google Redirect
GET http://localhost:3000/auth/google/redirect

# Movie Controller Requests

### Create Movie
# Only for Admin, Require [ADMIN_TOKEN]
POST http://localhost:3000/movie
Content-Type: application/json
Authorization: Bearer <PASTE_YOUR_ACCESS_TOKEN_HERE>

{
  "title": "Movie Title",
  "description": "Movie description here",
  "releaseDate": "2024-12-20",
  "genre": "Action",
  "duration": 120
}

### Stream Movie
GET http://localhost:3000/movie/stream/{title}

### Get All Movies
GET http://localhost:3000/movie

### Get Movie by Title
GET http://localhost:3000/movie/{title}

### Update Movie
# Only for Admin, Require [ADMIN_TOKEN]
PATCH http://localhost:3000/movie/{title}
Content-Type: application/json
Authorization: Bearer <PASTE_YOUR_ACCESS_TOKEN_HERE>

{
  "description": "Updated movie description",
  "duration": 130
}

### Delete Movie
# Only for Admin, Require [ADMIN_TOKEN]
DELETE http://localhost:3000/movie/{title}
Authorization: Bearer <PASTE_YOUR_ACCESS_TOKEN_HERE>
